const products = [
  {
    id: 1,
    img: "images/product-jacket.jpg",
    name: "Aeron Vapor Shell",
    sub: "Kurtka wiatroodporna",
    price: 589,
    oldPrice: null,
    badge: "new",
  },
  {
    id: 2,
    img: "images/product-shoes.jpg",
    name: "Aeron Pulse X",
    sub: "Buty do biegania",
    price: 749,
    oldPrice: 899,
    badge: "sale",
  },
  {
    id: 3,
    img: "images/product-shorts.jpg",
    name: "Aeron Flex Pro",
    sub: "Spodenki treningowe",
    price: 249,
    oldPrice: null,
    badge: null,
  },
  {
    id: 4,
    img: "images/product-tee.jpg",
    name: "Aeron Core Tee",
    sub: "Koszulka kompresyjna",
    price: 189,
    oldPrice: null,
    badge: "new",
  },
  {
    id: 5,
    img: "images/product-backpack.jpg",
    name: "Aeron Trail Pack",
    sub: "Plecak do biegania",
    price: 449,
    oldPrice: 520,
    badge: "sale",
  },
  {
    id: 6,
    img: "images/product-cap.jpg",
    name: "Aeron Speed Cap",
    sub: "Czapka aerodynamiczna",
    price: 149,
    oldPrice: null,
    badge: null,
  },
];
